Repository CapstoneDavinchi/Capstone_Back, pull requests merged in 2024-06, with the labels that each got.

#42 ✨ feat: OAuth2 구현
  build.gradle
  src/main/java/Capstone/Davinchi_Server/global/config/SecurityConfig.java
  src/main/java/Capstone/Davinchi_Server/global/config/WebSecurityConfig.java
  src/main/java/Capstone/Davinchi_Server/global/jwt/JwtTokenUtil.java
  src/main/java/Capstone/Davinchi_Server/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/Capstone/Davinchi_Server/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/Capstone/Davinchi_Server/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/Capstone/Davinchi_Server/oauth2/OAuthAttributes.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/main/resources/templates/index.html
Labels: :sparkles: feat

#44 :ambulance: bug: application.yml 수정
  src/main/resources/application.yml
Labels: 🐛 bug

#46 :sparkles: feat: gcs 사진 삭제 로직 추가
  src/main/java/Capstone/Davinchi_Server/image/StorageController.java
  src/main/java/Capstone/Davinchi_Server/image/StorageService.java
Labels: :sparkles: feat

#47 ✨ feat: 예술작품 갤러리 게시글 crud 구현
  build.gradle
  src/main/java/Capstone/Davinchi_Server/gallery/controller/GalleryPostController.java
  src/main/java/Capstone/Davinchi_Server/gallery/converter/GalleryImgConverter.java
  src/main/java/Capstone/Davinchi_Server/gallery/converter/GalleryPostConverter.java
  src/main/java/Capstone/Davinchi_Server/gallery/dto/GalleryPostDetails.java
  src/main/java/Capstone/Davinchi_Server/gallery/dto/GalleryPostReq.java
  src/main/java/Capstone/Davinchi_Server/gallery/dto/GalleryPostRes.java
  src/main/java/Capstone/Davinchi_Server/gallery/entity/GalleryFeedback.java
  src/main/java/Capstone/Davinchi_Server/gallery/entity/GalleryFeedbackImg.java
  src/main/java/Capstone/Davinchi_Server/gallery/entity/GalleryPost.java
  src/main/java/Capstone/Davinchi_Server/gallery/entity/GalleryPostImg.java
  src/main/java/Capstone/Davinchi_Server/gallery/entity/enums/GalleryCategory.java
  src/main/java/Capstone/Davinchi_Server/gallery/repository/GalleryPostImgRepository.java
  src/main/java/Capstone/Davinchi_Server/gallery/repository/GalleryPostLikeRepository.java
  src/main/java/Capstone/Davinchi_Server/gallery/repository/GalleryPostRepository.java
  src/main/java/Capstone/Davinchi_Server/gallery/service/GalleryPostCommandService.java
  src/main/java/Capstone/Davinchi_Server/gallery/service/GalleryPostQueryService.java
  src/main/java/Capstone/Davinchi_Server/global/config/OctetStreamReadMsgConverter.java
  src/main/java/Capstone/Davinchi_Server/global/config/WebConfig.java
  src/main/java/Capstone/Davinchi_Server/global/exception/ApiResponseStatus.java
Labels: :sparkles: feat

#48 ✨ feat: 미술 장터 crud 구현
  src/main/java/Capstone/Davinchi_Server/global/exception/ApiResponseStatus.java
  src/main/java/Capstone/Davinchi_Server/market/controller/MarketController.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketReq.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketRes.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketImg.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPost.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPostLike.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketPhotoRepository.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketRepository.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketPhotoService.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketService.java
Labels: :sparkles: feat

#49 Revert "✨ feat: 미술 장터 crud 구현"
  src/main/java/Capstone/Davinchi_Server/global/exception/ApiResponseStatus.java
  src/main/java/Capstone/Davinchi_Server/market/controller/MarketController.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketReq.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketRes.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketImg.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPost.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPostLike.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketPhotoRepository.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketRepository.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketPhotoService.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketService.java
Labels: 🐛 bug

#50 ✨ feat: 미술 장터 crud 구현
  src/main/java/Capstone/Davinchi_Server/market/controller/MarketController.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketReq.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketRes.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketImg.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPost.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPostLike.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketPhotoRepository.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketRepository.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketPhotoService.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketService.java
Labels: :sparkles: feat

#51 Revert "✨ feat: 미술 장터 crud 구현"
  src/main/java/Capstone/Davinchi_Server/market/controller/MarketController.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketReq.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketRes.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketImg.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPost.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPostLike.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketPhotoRepository.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketRepository.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketPhotoService.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketService.java
Labels: 🐛 bug

#52 ✨feat: 미술 장터 crud 구현
  src/main/java/Capstone/Davinchi_Server/global/exception/ApiResponseStatus.java
Labels: :sparkles: feat

#54 ✨feat: 미술 장터 crud 구현
  src/main/java/Capstone/Davinchi_Server/global/exception/ApiResponseStatus.java
  src/main/java/Capstone/Davinchi_Server/market/controller/MarketController.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketReq.java
  src/main/java/Capstone/Davinchi_Server/market/dto/MarketRes.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketImg.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPost.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPostLike.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketPhotoRepository.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketRepository.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketPhotoService.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketService.java
Labels: :sparkles: feat

#58 ✨ feat: 장터 좋아요 및 검색 기능 구현
  src/main/java/Capstone/Davinchi_Server/chat/controller/ChatRoomController.java
  src/main/java/Capstone/Davinchi_Server/market/controller/MarketController.java
  src/main/java/Capstone/Davinchi_Server/market/entity/MarketPost.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketLikeRepository.java
  src/main/java/Capstone/Davinchi_Server/market/repository/MarketRepository.java
  src/main/java/Capstone/Davinchi_Server/market/service/MarketService.java
Labels: :sparkles: feat

#59 refactor: oauth2 관련 수정
  build.gradle
  src/main/java/Capstone/Davinchi_Server/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: enhancement
